//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiamGia()
        {
            this.SoDatTours = new HashSet<SoDatTour>();
        }
    
        public string MaGiamGia { get; set; }
        public string TenSuKienGiamGia { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> PhanTramGiamGia { get; set; }
        public Nullable<decimal> SoTienGiamGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoDatTour> SoDatTours { get; set; }
    }
}
