//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuyTour
    {
        public string MaHuyTour { get; set; }
        public string MaVe { get; set; }
        public string MaTHHuyVe { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
    
        public virtual ChinhSachHuyVe ChinhSachHuyVe { get; set; }
        public virtual ChiTietDatVe ChiTietDatVe { get; set; }
    }
}
