//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinhTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichTrinhTour()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public string MaLichTrinh { get; set; }
        public string TenCacDiaDanh { get; set; }
        public string Tinh { get; set; }
        public string KhachSan { get; set; }
        public Nullable<decimal> TienKS { get; set; }
        public string MoTaLichTrinh { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> NgayCapNhatGanNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
