//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DULICHEntiti : DbContext
    {
        public DULICHEntiti()
            : base("name=DULICHEntiti")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChinhSachHuyVe> ChinhSachHuyVes { get; set; }
        public virtual DbSet<ChiTietDatVe> ChiTietDatVes { get; set; }
        public virtual DbSet<GiamGia> GiamGias { get; set; }
        public virtual DbSet<HuyTour> HuyTours { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<LichTrinhTour> LichTrinhTours { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SoDatTour> SoDatTours { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
    
        public virtual int KhoiPhucVe(string mave)
        {
            var maveParameter = mave != null ?
                new ObjectParameter("mave", mave) :
                new ObjectParameter("mave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhoiPhucVe", maveParameter);
        }
    
        public virtual int HoanChoHuyVe(string maTour)
        {
            var maTourParameter = maTour != null ?
                new ObjectParameter("maTour", maTour) :
                new ObjectParameter("maTour", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoanChoHuyVe", maTourParameter);
        }
    
        public virtual int XoaNVTrongTour(string maTour)
        {
            var maTourParameter = maTour != null ?
                new ObjectParameter("maTour", maTour) :
                new ObjectParameter("maTour", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNVTrongTour", maTourParameter);
        }
    }
}
