//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.SoDatTours = new HashSet<SoDatTour>();
        }
    
        public string MaTour { get; set; }
        public string MaLichTrinh { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayVe { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string NguoiDieuHanh { get; set; }
        public Nullable<decimal> GiaVeTreEm { get; set; }
        public Nullable<decimal> GiaVeNguoiLon { get; set; }
        public Nullable<int> SoLuongVe { get; set; }
        public Nullable<int> SoLuongDaDat { get; set; }
        public Nullable<float> TinhTrang { get; set; }
    
        public virtual LichTrinhTour LichTrinhTour { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoDatTour> SoDatTours { get; set; }
    }
}
